version: '3'

services:
  app:
    build: .
    command: bash -c "yarn typeorm migration:run && yarn dev:server"
    networks:
      - default
      - app-connect
    ports:
      - '3333:3333'

    depends_on:
      - db

  db:
    image: postgres:12
    environment:
      POSTGRES_DB: 'finances'
      POSTGRES_USER: 'nodePostgres'
      POSTGRES_PASSWORD: 'docker'
    networks:
      - app-connect
    ports:
      - '5432:5432'

  mongodb:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

networks:
  default:
  app-connect:
    internal: True
