version: "3" ## especifica a versão do docker-compose file

services: ## Define um serviço
  app: ## nome do serviço
    build: . ## localização do dockerfile
    command: bash -c "yarn typeorm migration:run && yarn dev:server"
      # - yarn dev:server ## comando a executar
    networks:
      - default
      - app-connect
    ports:
      - "3333:3333" ## redirecionamento de porta quando chegar alguma requisição na porta 3000 chama o container na porta 3000
    # volumes:
    #   - .:/usr/app ## monitoro a pasta atual . e envio as alterações para /usr/app
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_DB: 'finances'
      POSTGRES_USER: 'nodePostgres'
      POSTGRES_PASSWORD: 'docker'
    networks:
      - app-connect
    # ports:
    #   - "5432:5432"

networks:
    default:
    app-connect:
      internal: True
